Numarataj.WebUI/Areas/Admin/Controllers/ResmiKurumController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using AutoMapper;
using Numarataj.DataAccess.Context;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Numarataj.Entity.Entities;
using Numarataj.WebUI.Helpers;
using Numarataj.DTO.DTOs.ResmiKurumDTOs;
namespace Numarataj.WebUI.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin,Personel")]
    [Area("Admin")]   
    public class ResmiKurumController : Controller
    {
        private readonly NumaratajDbContext _context;
        private readonly IMapper _mapper;

        public ResmiKurumController(NumaratajDbContext context, IMapper mapper)
        {
            _context = context;
            _mapper = mapper;
        }
        [HttpGet]
        [Route("ResmiKurum/index")]
        public async Task<IActionResult> Index()
        {
            var values = await _context.ResmiKurum.ToListAsync();
            var resultDtos = _mapper.Map<List<ResultResmiKurumDto>>(values);
            return View(resultDtos);
        }
        [HttpGet]
        [Route("ResmiKurum/Create")]
        public IActionResult CreateResmiKurum()
        {
            ViewBag.Mahalleler = Constants.Mahalleler;
            return View();
        }

        [HttpPost]
        [Route("ResmiKurum/Create")]
        public async Task<IActionResult> CreateResmiKurum(CreateResmiKurumDto createResmiKurumDto)
        {
            if (!ModelState.IsValid)
            {
                return View(createResmiKurumDto);
            }

            var resmiKurum = _mapper.Map<ResmiKurum>(createResmiKurumDto);
            await _context.ResmiKurum.AddAsync(resmiKurum);
            await _context.SaveChangesAsync();

            TempData["SuccessMessage"] = "Yeni Resmi Kurum Alanı Oluşturuldu";
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> UpdateResmiKurum(int belgeNoId)
        {
            var resmiKurum = await _context.ResmiKurum.FirstOrDefaultAsync(x => x.BelgeNoId == belgeNoId);
            if (resmiKurum == null)
            {
                return NotFound();
            }

            var updateResmiKurumDto = _mapper.Map<UpdateResmiKurumDto>(resmiKurum);
            ViewBag.MahalleListesi = Constants.Mahalleler.Select(m => new SelectListItem
            {
                Text = m,
                Value = m,
                Selected = m == updateResmiKurumDto.Mahalle
            }).ToList();

            return View("UpdateResmiKurum", updateResmiKurumDto);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UpdateResmiKurum(UpdateResmiKurumDto updateResmiKurumDto)
        {
            if (ModelState.IsValid)
            {
                var resmiKurum = await _context.ResmiKurum.FirstOrDefaultAsync(x => x.BelgeNoId == updateResmiKurumDto.BelgeNoId);
                if (resmiKurum == null)
                {
                    return NotFound();
                }

                _mapper.Map(updateResmiKurumDto, resmiKurum);
                _context.ResmiKurum.Update(resmiKurum);
                await _context.SaveChangesAsync();

                TempData["SuccessMessage"] = "Güncelleme işlemi başarılı!";
                return RedirectToAction("Index");
            }

            ViewBag.Mahalleler = Constants.Mahalleler;
            return View(updateResmiKurumDto);
        }


        [HttpPost]
        [Route("ResmiKurum/Delete/{id:int}")]
        public async Task<IActionResult> DeleteResmiKurum(int id)
        {
            var resmiKurum = await _context.ResmiKurum.FindAsync(id);
            if (resmiKurum == null)
            {
                return NotFound();
            }

            _context.ResmiKurum.Remove(resmiKurum);
            await _context.SaveChangesAsync();
            TempData["SuccessMessage"] = "Resmi Kurum başarıyla silindi";
            return RedirectToAction(nameof(Index));
        }

    }
}

Numarataj.WebUI/Areas/Admin/Views/ResmiKurum/CreateResmiKurum.cshtml
@model CreateResmiKurumDto
@{
    ViewData["Title"] = "Yeni Resmi Kurum Ekleme Sayfası";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-..." crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
</head>
<style>
    .custom-form-container {
        background-color: #e6e0f8; /* Açık mor renk */
        padding: 20px; /* Formun çevresine dolgu */
        border-radius: 8px; /* Kenarları yuvarlatmak için */
        max-width: 1000px; /* Daha geniş bir maksimum genişlik */
        width: 90%; /* Tam ekran genişliğinin %90'ı */
        margin: auto;
    }

</style>
<form id="resmiKurumForm" method="post" class="custom-form-container">
    <table class="table table-bordered">
        <tbody>
            <tr>
                <td>
                    <label for="TcKimlikNo" class="form-label">TC Kimlik No</label>
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fas fa-id-card"></i></span>
                        </div>
                        <input type="text" class="form-control" id="TcKimlikNo" name="TcKimlikNo"
                               placeholder="11 Haneli TC Kimlik No"
                               maxlength="11" minlength="11"
                               oninput="this.value = this.value.replace(/[^0-9]/g, '').slice(0, 11);">
                    </div>
                </td>
                <td>
                    <label for="Telefon" class="form-label">Telefon</label>
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fas fa-phone"></i></span>
                        </div>
                        <input type="text" class="form-control" id="Telefon" name="Telefon"
                               placeholder="Telefon Numaranız"
                               maxlength="11" oninput="this.value = this.value.replace(/[^0-9]/g, '').slice(0, 11);">
                    </div>
                </td>

            </tr>
            <tr>
                <td>
                    <label for="AdSoyad" class="form-label">Adı Soyadı</label>
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fas fa-user"></i></span>
                        </div>
                        <input type="text" class="form-control" id="AdSoyad" name="AdSoyad" placeholder="Ad ve Soyadını Girin" maxlength="100" oninput="this.value = this.value.toLocaleUpperCase('tr-TR');">
                    </div>
                </td>
                <td>
                    <label for="Mahalle" class="form-label">Mahalle</label>
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fas fa-map-marker-alt"></i></span>
                        </div>
                        <select id="Mahalle" name="Mahalle" class="form-control" required>
                            <option value="">Mahalle Seçiniz...</option>
                            @foreach (var mahalle in ViewBag.Mahalleler)
                            {
                                <option value="@mahalle">@mahalle</option>
                            }
                        </select>
                    </div>
                </td>
            </tr>
            <tr>
                <td>
                    <label for="CaddeSokak" class="form-label">Cadde/Sokak</label>
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fas fa-road"></i></span>
                        </div>
                        <input type="text" class="form-control" id="CaddeSokak" name="CaddeSokak"
                               placeholder="Cadde veya Sokak Adı"
                               maxlength="100"
                               oninput="this.value = this.value.toLocaleUpperCase('tr-TR');">
                    </div>
                </td>
                <td>
                    <label for="DisKapi" class="form-label">Dış Kapı No</label>
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fas fa-door-open"></i></span>
                        </div>
                        <input type="text" class="form-control" id="DisKapi" name="DisKapi"
                               placeholder="Dış Kapı No" maxlength="4"
                               oninput="this.value = this.value.toLocaleUpperCase('tr-TR');">
                    </div>
                </td>
            </tr>

            <tr>
                <td>
                    <label for="IcKapiNo" class="form-label">İç Kapı No</label>
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fas fa-door-closed"></i></span>
                        </div>
                        <input type="text" class="form-control" id="IcKapiNo" name="IcKapiNo"
                               placeholder="İç Kapı No" maxlength="4"
                               oninput="this.value = this.value.replace(/[^0-9]/g, '').slice(0, 4);">

                    </div>
                </td>
                <td>
                    <label for="AdresNo" class="form-label">Adres No (UAVT)</label>
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fas fa-hashtag"></i></span>
                        </div>
                        <input type="text" class="form-control" id="AdresNo" name="AdresNo"
                               placeholder="Adres No (UAVT)" maxlength="10"
                               oninput="this.value = this.value.slice(0, 10);">
                    </div>
                </td>


            </tr>

            <tr>
                <td>
                    <label for="Ada" class="form-label">Ada</label>
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fas fa-map"></i></span>
                        </div>
                        <input type="text" class="form-control" id="Ada" name="Ada"
                               placeholder="Ada No" maxlength="6"
                               oninput="this.value = this.value.replace(/[^0-9]/g, '').slice(0, 6);">
                    </div>
                </td>
                <td>
                    <label for="Parsel" class="form-label">Parsel</label>
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fas fa-map"></i></span>
                        </div>
                        <input type="text" class="form-control" id="Parsel" name="Parsel"
                               placeholder="Parsel No" maxlength="6"
                               oninput="this.value = this.value.replace(/[^0-9]/g, '').slice(0, 6);">
                    </div>
                </td>

            </tr>
             
            <tr>
                <td>
                    <input type="hidden" id="Tarih" name="Tarih" />
                </td>
                <td colspan="2" class="text-center">
                    <button type="submit" class="btn btn-primary">Kaydet</button>
                </td>
            </tr>
        </tbody>
    </table>
</form>
<script>
    document.addEventListener('DOMContentLoaded', function () {
        const today = new Date();

        // Yerel saat dilimine göre tarih ve saat formatı
        const offset = today.getTimezoneOffset() * 60000; // dakika cinsinden offset'i milisaniyeye çevir
        const localTime = new Date(today.getTime() - offset);

        // Formatlayarak tarih ve saati al
        const formattedDate = localTime.toISOString().substring(0, 16);
        document.getElementById('Tarih').value = formattedDate;
    });
</script>
<script>
    document.addEventListener('DOMContentLoaded', function () {
        const form = document.getElementById('resmiKurumForm');

        form.addEventListener('input', function (event) {
            const input = event.target;

            // Yalnızca metin ve telefon alanlarında dönüşüm yap
            if (input.type === 'text' || input.type === 'tel') {
                input.value = input.value.toLocaleUpperCase('tr-TR'); // Türkçe büyük harf dönüştürme
            }
        });

        form.addEventListener('submit', function (event) {
            // Submit sırasında bir daha kontrol etmek için
            const inputs = form.querySelectorAll('input');
            inputs.forEach(function (input) {
                if (input.type === 'text' || input.type === 'tel') {
                    input.value = input.value.toLocaleUpperCase('tr-TR');
                }
            });
        });
    });
</script>

Numarataj.WebUI/Areas/Admin/Views/ResmiKurum/Index.cshtml
@model List<ResultResmiKurumDto>

@{
    ViewData["Title"] = "RESMİ KURUM SAYFASI";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<style>
    .btn-outline-danger {
        background-color: #d9534f;
        color: white;
    }

    .btn-outline-info {
        background-color: #5bc0de;
        color: white;
    }

    .btn-outline-primary {
        background-color: #0275d8;
        color: white;
    }

    .btn-outline-success {
        background-color: #5cb85c;
        color: white;
    }

    #resmiKurumTable tbody tr:hover > td {
        background-color: #91c6ff !important;
    }

    .container {
        max-width: 100%;
        margin: 0;
        padding: 0;
    }

    .btn-group .btn {
        margin-right: 5px;
    }

    .top-button-container {
        display: flex;
        position: relative; /* Konumlandırmayı göreli yapar */
        justify-content: flex-end;
        margin-bottom: 10px;
    }

        .top-button-container a {
            position: absolute;
            top: 5px; /* Butonu aşağı kaydırır */
            right: 0;
            z-index: 10; /* Butonu öne getirir */
        }
</style>

@if (TempData["SuccessMessage"] != null)
{
    <div id="successMessage" class="alert alert-success" role="alert">
        @TempData["SuccessMessage"]
    </div>
}

<div class="container mt-2">
    <div class="top-button-container">
        <a asp-action="CreateResmiKurum" asp-controller="ResmiKurum" asp-area="Admin" class="btn btn-outline-primary">Resmi Kurum Ekle</a>
    </div>
    <table id="resmiKurumTable" class="display table table-striped table-bordered" style="width:100%">
        <thead>
            <tr>
                <th>B.No</th>
                <th>TC</th>
                <th>Ad/Soyad</th>
                <th>Tarih</th>
                <th>Tel</th>
                <th>Mahalle</th>
                <th>Sokak</th>
                <th>D.Kapı</th>
                <th>İç Kapı</th>
                <th>İşlem</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.BelgeNoId</td>
                    <td class="tc-kimlik">
                        <span class="tc-value">@item.TcKimlikNo</span>
                        <input type="checkbox" class="hide-tc-checkbox" />
                    </td>

                    <td>@item.AdSoyad</td>
                    <td>@item.Tarih</td>
                    <td>@item.Telefon</td>
                    <td>@item.Mahalle</td>
                    <td>@item.CaddeSokak</td>
                    <td>@item.DisKapi</td>
                    <td>@item.IcKapiNo</td>
                    <td>
                        <div class="btn-group">
                            <button class="btn btn-sm btn-outline-danger" data-toggle="modal" data-target="#deleteModal-@item.BelgeNoId">
                                <i class="fas fa-trash-alt"></i>
                            </button>
                            <a asp-area="Admin" asp-controller="ResmiKurum" asp-action="UpdateResmiKurum" asp-route-belgeNoId="@item.BelgeNoId" class="btn btn-sm btn-outline-success">
                                <i class="fas fa-edit"></i>
                            </a>
                            <a href="#"
                               class="btn btn-sm btn-outline-info generate-pdf-button"
                               data-id="@item.BelgeNoId"
                               data-title="RESMİ KURUM"
                               data-type="4">
                                <i class="fas fa-file-pdf"></i> PDF
                            </a>

                        </div>

                        <!-- Modal Structure for Delete Confirmation -->
                        <div class="modal fade" id="deleteModal-@item.BelgeNoId" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel-@item.BelgeNoId" aria-hidden="true">
                            <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                    <div class="modal-header bg-danger text-white">
                                        <h5 class="modal-title" id="deleteModalLabel-@item.BelgeNoId">Silme Onayı</h5>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                    <div class="modal-body">
                                        Bu kaydı silmek istediğinize emin misiniz?
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Kapat</button>
                                        <form asp-action="DeleteResmiKurum" asp-controller="ResmiKurum" asp-area="Admin" asp-route-id="@item.BelgeNoId" method="post" style="display:inline;">
                                            <button type="submit" class="btn btn-danger">Sil</button>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>
<script>
    document.querySelectorAll('.generate-pdf-button').forEach(button => {
         button.addEventListener('click', function (event) {
             event.preventDefault();

             const id = this.getAttribute('data-id');
             const title = this.getAttribute('data-title');
             const type = this.getAttribute('data-type');

             // Aynı satırdaki TC gizleme checkbox'ının durumunu kontrol et
             const checkbox = this.closest('tr').querySelector('.hide-tc-checkbox');
             const isTcHidden = checkbox && checkbox.checked ? "true" : "false";

             // PDF URL'sine `isTcHidden` parametresini ekleyerek gönder
             const url = `/Admin/Pdf/GeneratePdf?id=${id}&title=${encodeURIComponent(title)}&type=${type}&isTcHidden=${isTcHidden}`;

             window.open(url, '_blank');
         });
     });

    

    // Başarı mesajını gizle
    setTimeout(function () {
        const successMessage = document.getElementById("successMessage");
        if (successMessage) {
            successMessage.style.display = "none";
        }
    }, 2000);
</script>

Numarataj.WebUI/Areas/Admin/Views/ResmiKurum/UpdateResmiKurum.cshtml
@model UpdateResmiKurumDto
@{
    ViewData["Title"] = "Resmi Kurum Güncelleme Sayfası";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-..." crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
</head>
<style>
    .custom-form-container {
        background-color: #e6e0f8; /* Açık mor renk */
        padding: 20px; /* Formun çevresine dolgu */
        border-radius: 8px; /* Kenarları yuvarlatmak için */
    }
</style>

<form id="resmiKurumForm" method="post" asp-area="Admin" asp-controller="ResmiKurum" asp-action="UpdateResmiKurum" class="custom-form-container">
    <input type="hidden" name="BelgeNoId" value="@Model.BelgeNoId" />
    @Html.AntiForgeryToken()
    <table class="table table-bordered">
        <tbody>
            <tr>
                <td>
                    <label for="TcKimlikNo" class="form-label">TC Kimlik No</label>
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fas fa-id-card"></i></span>
                        </div>
                        <input type="text" class="form-control" id="TcKimlikNo" name="TcKimlikNo"
                               placeholder="TC Kimlik No" maxlength="11"
                               value="@(Model?.TcKimlikNo ?? "")"
                               oninput="this.value = this.value.replace(/[^0-9]/g, '').slice(0, 11);">
                    </div>
                </td>
                <td>
                    <label for="Telefon" class="form-label">Telefon</label>
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fas fa-phone"></i></span>
                        </div>
                        <input type="text" class="form-control" id="Telefon" name="Telefon"
                               placeholder="Telefon Numaranız" maxlength="11"
                               value="@(Model?.Telefon ?? "")"
                               oninput="this.value = this.value.replace(/[^0-9]/g, '').slice(0, 11);">
                    </div>
                </td>
            </tr>
            <tr>
                <td>
                    <label for="AdSoyad" class="form-label">Adı Soyadı</label>
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fas fa-user"></i></span>
                        </div>
                        <input type="text" class="form-control" id="AdSoyad" name="AdSoyad"
                               placeholder="Adı Soyadı" maxlength="100"
                               value="@(Model?.AdSoyad ?? "")"
                               oninput="this.value = this.value.toLocaleUpperCase('tr-TR');">
                    </div>
                </td>
                <td>
                    <label for="inputMahalle" class="form-label">Mahalle</label>
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fas fa-map-marker-alt"></i></span>
                        </div>
                        @Html.DropDownListFor(model => model.Mahalle,
                                 (IEnumerable<SelectListItem>)ViewBag.MahalleListesi,
                                 new { @class = "form-control", id = "inputMahalle", required = "required" })
                    </div>
                    <span class="text-danger" id="mahalleError" style="display: none;">Lütfen bir mahalle seçiniz!</span>
                </td>
            </tr>
            <tr>
                <td>
                    <label for="CaddeSokak" class="form-label">Cadde/Sokak</label>
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fas fa-road"></i></span>
                        </div>
                        <input type="text" class="form-control" id="CaddeSokak" name="CaddeSokak"
                               placeholder="Cadde/Sokak" maxlength="100"
                               value="@(Model?.CaddeSokak ?? "")"
                               oninput="this.value = this.value.toLocaleUpperCase('tr-TR');">
                    </div>
                </td>
                <td>
                    <label for="DisKapi" class="form-label">Dış Kapı No</label>
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fas fa-door-open"></i></span>
                        </div>
                        <input type="text" class="form-control" id="DisKapi" name="DisKapi"
                               placeholder="Dış Kapı No" maxlength="4"
                               value="@(Model?.DisKapi ?? "")"
                               oninput="this.value = this.value.toLocaleUpperCase('tr-TR');">
                    </div>
                </td>
            </tr>
            <tr>
                <td>
                    <label for="İcKapiNo" class="form-label">İç Kapı No</label>
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fas fa-door-closed"></i></span>
                        </div>
                        <input type="text" class="form-control" id="IcKapiNo" name="IcKapiNo"
                               placeholder="İç Kapı No" maxlength="4"
                               value="@(Model?.IcKapiNo ?? "")"
                               oninput="this.value = this.value.replace(/[^0-9]/g, '').slice(0, 4);">
                    </div>
                </td>
                <td>
                    <label for="AdresNo" class="form-label">Adres No (UAVT)</label>
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fas fa-hashtag"></i></span>
                        </div>
                        <input type="text" class="form-control" id="AdresNo" name="AdresNo"
                               placeholder="Adres No (UAVT)" maxlength="10"
                               value="@(Model?.AdresNo ?? "")"
                               oninput="this.value = this.value.slice(0, 10);">
                    </div>
                </td>
            </tr>
            <tr>
                <td>
                    <label for="Ada" class="form-label">Ada</label>
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fas fa-map"></i></span>
                        </div>
                        <input type="text" class="form-control" id="Ada" name="Ada"
                               placeholder="Ada" maxlength="6"
                               value="@(Model?.Ada ?? "")"
                               oninput="this.value = this.value.replace(/[^0-9]/g, '').slice(0, 6);">
                    </div>
                </td>
                 <td>
                    <label for="Parsel" class="form-label">Parsel</label>
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fas fa-map"></i></span>
                        </div>
                        <input type="text" class="form-control" id="Parsel" name="Parsel"
                               placeholder="Parsel" maxlength="6"
                               value="@(Model?.Parsel ?? "")"
                               oninput="this.value = this.value.replace(/[^0-9]/g, '').slice(0, 6);">
                    </div>
                </td>
            </tr>
            <tr>
                <td>
                    <input type="hidden" id="Tarih" name="Tarih" value="@Model.Tarih" />
                </td>
                <td colspan="2" class="text-center">
                    <button type="submit" class="btn btn-primary">Güncelle</button>
                </td>
            </tr>
        </tbody>
    </table>
</form>

<script>
    document.addEventListener('DOMContentLoaded', function () {
        const today = new Date();

        // Yerel saat dilimine göre tarih ve saat formatı
        const offset = today.getTimezoneOffset() * 60000; // dakika cinsinden offset'i milisaniyeye çevir
        const localTime = new Date(today.getTime() - offset);

        // Formatlayarak tarih ve saati al
        const formattedDate = localTime.toISOString().substring(0, 16);
        document.getElementById('Tarih').value = formattedDate;
    });
</script>
<script>
    document.addEventListener('DOMContentLoaded', function () {
        const form = document.getElementById('resmiKurumForm');

        form.addEventListener('input', function (event) {
            const input = event.target;

            // Yalnızca metin ve telefon alanlarında dönüşüm yap
            if (input.type === 'text' || input.type === 'tel') {
                input.value = input.value.toLocaleUpperCase('tr-TR'); // Türkçe büyük harf dönüştürme
            }
        });

        form.addEventListener('submit', function (event) {
            // Submit sırasında bir daha kontrol etmek için
            const inputs = form.querySelectorAll('input');
            inputs.forEach(function (input) {
                if (input.type === 'text' || input.type === 'tel') {
                    input.value = input.value.toLocaleUpperCase('tr-TR');
                }
            });
        });
    });
</script>