Numarataj.WebUI/Areas/Admin/Controllers/SahaCalismasiController.cs
using Microsoft.AspNetCore.Mvc;
using Numarataj.WebUI.Helpers;
using Numarataj.DTO.DTOs.SahaCalismasiDTOs;
using Microsoft.AspNetCore.Authorization;
using AutoMapper;
using Numarataj.DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Numarataj.Entity.Entities;
using Microsoft.AspNetCore.Mvc.Rendering;
namespace Numarataj.WebUI.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin,Personel")]
    [Area("Admin")]  
    public class SahaCalismasiController : Controller
    {
        private readonly NumaratajDbContext _context;
        private readonly IMapper _mapper;

        public SahaCalismasiController(NumaratajDbContext context, IMapper mapper)
        {
            _context = context;
            _mapper = mapper;
        }
        [HttpGet]
        [Route("SahaCalismasi/index")]
        public async Task<IActionResult> Index()
        {
            var values = await _context.SahaCalismasi.ToListAsync();
            var resultDtos = _mapper.Map<List<ResultSahaCalismasiDto>>(values);
            return View(resultDtos);
        }
        [HttpGet]
        [Route("SahaCalismasi/Create")]
        public IActionResult CreateSahaCalismasi()
        {
            ViewBag.Mahalleler = Constants.Mahalleler;
            return View();
        }

        [HttpPost]
        [Route("SahaCalismasi/Create")]
        public async Task<IActionResult> CreateSahaCalismasi(CreateSahaCalismasiDto createSahaCalismasiDto)
        {
            if (!ModelState.IsValid)
            {
                return View(createSahaCalismasiDto);
            }

            var sahaCalismasi = _mapper.Map<SahaCalismasi>(createSahaCalismasiDto);
            await _context.SahaCalismasi.AddAsync(sahaCalismasi);
            await _context.SaveChangesAsync();

            TempData["SuccessMessage"] = "Yeni Saha Çalışma Alanı Oluşturuldu";
            return RedirectToAction(nameof(Index));
        }
        [HttpGet]
        public async Task<IActionResult> UpdateSahaCalismasi(int belgeNoId)
        {
            var sahaCalismasi = await _context.SahaCalismasi.FirstOrDefaultAsync(x => x.BelgeNoId == belgeNoId);
            if (sahaCalismasi == null)
            {
                return NotFound();
            }

            var updateSahaCalismasiDto = _mapper.Map<UpdateSahaCalismasiDto>(sahaCalismasi);
            ViewBag.MahalleListesi = Constants.Mahalleler.Select(m => new SelectListItem
            {
                Text = m,
                Value = m,
                Selected = m == updateSahaCalismasiDto.Mahalle
            }).ToList();

            return View("UpdateSahaCalismasi", updateSahaCalismasiDto);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UpdateSahaCalismasi(UpdateSahaCalismasiDto updateSahaCalismasiDto)
        {
            if (ModelState.IsValid)
            {
                var sahaCalismasi = await _context.SahaCalismasi.FirstOrDefaultAsync(x => x.BelgeNoId == updateSahaCalismasiDto.BelgeNoId);
                if (sahaCalismasi == null)
                {
                    return NotFound();
                }

                _mapper.Map(updateSahaCalismasiDto, sahaCalismasi);
                _context.SahaCalismasi.Update(sahaCalismasi);
                await _context.SaveChangesAsync();

                TempData["SuccessMessage"] = "Güncelleme işlemi başarılı!";
                return RedirectToAction("Index");
            }

            ViewBag.Mahalleler = Constants.Mahalleler;
            return View(updateSahaCalismasiDto);
        }


        [HttpPost]
        [Route("SahaCalismasi/Delete/{id:int}")]
        public async Task<IActionResult> DeleteSahaCalismasi(int id)
        {
            var sahaCalismasi = await _context.SahaCalismasi.FindAsync(id);
            if (sahaCalismasi == null)
            {
                return NotFound();
            }

            _context.SahaCalismasi.Remove(sahaCalismasi);
            await _context.SaveChangesAsync();
            TempData["SuccessMessage"] = "Saha Çalışması başarıyla silindi";
            return RedirectToAction(nameof(Index));
        }


    }
}

Numarataj.WebUI/Areas/Admin/Views/SahaCalismasi/CreateSahaCalismasi.cshtml
@model CreateSahaCalismasiDto
@{
    ViewData["Title"] = "Yeni Saha Çalışması Sayfası";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-..." crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
</head>
<style>
    .custom-form-container {
        background-color: #e6e0f8; /* Açık mor renk */
        padding: 20px; /* Formun çevresine dolgu */
        border-radius: 8px; /* Kenarları yuvarlatmak için */
        max-width: 1000px; /* Daha geniş bir maksimum genişlik */
        width: 90%; /* Tam ekran genişliğinin %90'ı */
        margin: auto;
    }
</style>
<form id="sahaCalismasiForm" method="post" class="custom-form-container">
    <table class="table table-bordered">
        <tbody>
            <tr>
                <td>
                    <label for="AdSoyad" class="form-label">Adı Soyadı</label>
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fas fa-user"></i></span>
                        </div>
                        <input type="text" class="form-control" id="AdSoyad" name="AdSoyad" placeholder="Ad ve Soyadını Girin" maxlength="100" oninput="this.value = this.value.toLocaleUpperCase('tr-TR');">
                    </div>
                </td>
                <td>
                    <label for="Mahalle" class="form-label">Mahalle</label>
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fas fa-map-marker-alt"></i></span>
                        </div>
                        <select id="Mahalle" name="Mahalle" class="form-control" required>
                            <option value="">Mahalle Seçiniz...</option>
                            @foreach (var mahalle in ViewBag.Mahalleler)
                            {
                                <option value="@mahalle">@mahalle</option>
                            }
                        </select>
                    </div>
                </td>
            </tr>
            <tr>
                <td>
                    <label for="DisKapi" class="form-label">Dış Kapı No</label>
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fas fa-door-open"></i></span>
                        </div>
                        <input type="text" class="form-control" id="DisKapi" name="DisKapi"
                               placeholder="Dış Kapı No" maxlength="4"
                               oninput="this.value = this.value.toLocaleUpperCase('tr-TR');">
                    </div>
                </td>
                <td>
                    <label for="IcKapiNo" class="form-label">İç Kapı No</label>
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fas fa-door-closed"></i></span>
                        </div>
                        <input type="text" class="form-control" id="IcKapiNo" name="IcKapiNo"
                               placeholder="İç Kapı No" maxlength="4"
                               oninput="this.value = this.value.replace(/[^0-9]/g, '').slice(0, 4);">

                    </div>
                </td>
            </tr>
            <tr>
                <td>
                    <label for="Ada" class="form-label">Ada</label>
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fas fa-map"></i></span>
                        </div>
                        <input type="text" class="form-control" id="Ada" name="Ada" placeholder="Ada" maxlength="6">
                    </div>
                </td>
                <td>
                    <label for="Parsel" class="form-label">Parsel</label>
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fas fa-map"></i></span>
                        </div>
                        <input type="text" class="form-control" id="Parsel" name="Parsel" placeholder="Parsel" maxlength="6">
                    </div>
                </td>
                
            </tr>

            <tr>
                <td>
                    <label for="CaddeSokak" class="form-label">Cadde/Sokak</label>
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fas fa-road"></i></span>
                        </div>
                        <input type="text" class="form-control" id="CaddeSokak" name="CaddeSokak"
                               placeholder="Cadde veya Sokak Adı"
                               maxlength="100"
                               oninput="this.value = this.value.toLocaleUpperCase('tr-TR');">

                    </div>
                </td>
            </tr>
            <tr>
                <td colspan="2" class="text-center">
                    <button type="submit" class="btn btn-primary">Kaydet</button>
                </td>
                <td>
                    <input type="hidden" id="Tarih" name="Tarih" />
                </td>
            </tr>
        </tbody>
    </table>
</form>
<script>
    document.addEventListener('DOMContentLoaded', function () {
        const today = new Date();

        // Yerel saat dilimine göre tarih ve saat formatı
        const offset = today.getTimezoneOffset() * 60000; // dakika cinsinden offset'i milisaniyeye çevir
        const localTime = new Date(today.getTime() - offset);

        // Formatlayarak tarih ve saati al
        const formattedDate = localTime.toISOString().substring(0, 16);
        document.getElementById('Tarih').value = formattedDate;
    });
</script>
<script>
    document.addEventListener('DOMContentLoaded', function () {
        const form = document.getElementById('sahaCalismasiForm');

        form.addEventListener('input', function (event) {
            const input = event.target;

            // Yalnızca metin ve telefon alanlarında dönüşüm yap
            if (input.type === 'text' || input.type === 'tel') {
                input.value = input.value.toLocaleUpperCase('tr-TR'); // Türkçe büyük harf dönüştürme
            }
        });

        form.addEventListener('submit', function (event) {
            // Submit sırasında bir daha kontrol etmek için
            const inputs = form.querySelectorAll('input');
            inputs.forEach(function (input) {
                if (input.type === 'text' || input.type === 'tel') {
                    input.value = input.value.toLocaleUpperCase('tr-TR');
                }
            });
        });
    });
</script>

Numarataj.WebUI/Areas/Admin/Views/SahaCalismasi/Index.cshtml
@model List<ResultSahaCalismasiDto>

@{
    ViewData["Title"] = "SAHA ÇALIŞMASI SAYFASI";

    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<style>
    .btn-outline-danger {
        background-color: #d9534f;
        color: white;
    }

    .btn-outline-info {
        background-color: #5bc0de;
        color: white;
    }

    .btn-outline-primary {
        background-color: #0275d8;
        color: white;
    }

    .btn-outline-success {
        background-color: #5cb85c;
        color: white;
    }

    #sahaCalismasiTable tbody tr:hover > td {
        background-color: #91c6ff !important;
    }

    .container {
        max-width: 100%;
        margin: 0;
        padding: 0;
    }

    table.dataTable {
        margin: 0;
    }

    .btn-group .btn {
        margin-right: 5px;
    }

    .btn-group {
        display: flex;
        gap: 5px;
    }

    .alert-container {
        margin-top: 10px;
    }

    .top-button-container {
        display: flex;
        position: relative;
        justify-content: flex-end;
        margin-bottom: 10px;
    }

        .top-button-container a {
            position: absolute;
            top: 5px;
            right: 0;
            z-index: 10;
        }
</style>

@if (TempData["SuccessMessage"] != null)

{
    <div id="successMessage" class="alert alert-success" role="alert">
        @TempData["SuccessMessage"]
    </div>
}

<div class="container mt-2">
    <div class="top-button-container">
        <a asp-action="CreateSahaCalismasi" asp-controller="SahaCalismasi" asp-area="Admin" class="btn btn-outline-primary">Saha Çalışması Ekle</a>
    </div>
    <table id="sahaCalismasiTable" class="display table table-striped table-bordered" style="width:100%">
        <thead>
            <tr>
                <th>B.No</th>
                <th>Ad Soyad</th>
                <th>Tarih</th>
                <th>Mahalle</th>
                <th>Dış Kapı</th>
                <th>Ada</th>
                <th>Parsel</th>
                <th>İşlem</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.BelgeNoId</td>
                    <td>@item.AdSoyad</td>
                    <td>@item.Tarih</td>
                    <td>@item.Mahalle</td>
                    <td>@item.DisKapi</td>
                    <td>@item.Ada</td>
                    <td>@item.Parsel</td>
                    <td>
                        <div class="btn-group">
                            <button class="btn btn-sm btn-outline-danger" data-toggle="modal" data-target="#deleteModal-@item.BelgeNoId">
                                <i class="fas fa-trash-alt"></i>
                            </button>
                            <a asp-action="UpdateSahaCalismasi" asp-area="Admin" asp-controller="SahaCalismasi" asp-route-belgeNoId="@item.BelgeNoId" class="btn btn-sm btn-outline-success">
                                <i class="fas fa-edit"></i>
                            </a>
                            <a href="#"
                               class="btn btn-sm btn-outline-info generate-pdf-button"
                               data-id="@item.BelgeNoId"
                               data-title="SAHA ÇALIŞMASI"
                               data-type="3">
                                <i class="fas fa-file-pdf"></i> PDF
                            </a>
                        </div>
                    </td>
                </tr>

                <!-- Modal Structure for Delete Confirmation -->
                <div class="modal fade" id="deleteModal-@item.BelgeNoId" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel-@item.BelgeNoId" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header bg-danger text-white">
                                <h5 class="modal-title" id="deleteModalLabel-@item.BelgeNoId">Silme Onayı</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                Bu kaydı silmek istediğinize emin misiniz?
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">Vazgeç</button>
                                <form asp-action="DeleteSahaCalismasi" asp-controller="SahaCalismasi" asp-area="Admin" asp-route-id="@item.BelgeNoId" method="post" style="display:inline;">
                                    <button type="submit" class="btn btn-danger">Onayla</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </tbody>
    </table>
</div>

<script>
    document.querySelectorAll('.generate-pdf-button').forEach(button => {
         button.addEventListener('click', function (event) {
             event.preventDefault();

             const id = this.getAttribute('data-id');
             const title = this.getAttribute('data-title');
             const type = this.getAttribute('data-type');

             // Aynı satırdaki TC gizleme checkbox'ının durumunu kontrol et
             const checkbox = this.closest('tr').querySelector('.hide-tc-checkbox');
             const isTcHidden = checkbox && checkbox.checked ? "true" : "false";

             // PDF URL'sine `isTcHidden` parametresini ekleyerek gönder
             const url = `/Admin/Pdf/GeneratePdf?id=${id}&title=${encodeURIComponent(title)}&type=${type}&isTcHidden=${isTcHidden}`;

             window.open(url, '_blank');
         });
     });

    // Başarı mesajını gizle
    setTimeout(function () {
        const successMessage = document.getElementById("successMessage");
        if (successMessage) {
            successMessage.style.display = "none";
        }
    }, 2000);
</script>

Numarataj.WebUI/Areas/Admin/Views/SahaCalismasi/UpdateSahaCalismasi.cshtml
@model UpdateSahaCalismasiDto

@{
    ViewData["Title"] = "Saha Çalışması Güncelleme Sayfası";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-..." crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
</head>
<style>
    .custom-form-container {
        background-color: #e6e0f8; /* Açık mor renk */
        padding: 20px; /* Formun çevresine dolgu */
        border-radius: 8px; /* Kenarları yuvarlatmak için */
        max-width: 1000px; /* Daha geniş bir maksimum genişlik */
        width: 90%; /* Tam ekran genişliğinin %90'ı */
        margin: auto;
    }
</style>

<form id="sahaCalismasiForm" method="post" asp-area="Admin" asp-controller="SahaCalismasi" asp-action="UpdateSahaCalismasi" class="custom-form-container">
    <input type="hidden" name="BelgeNoId" value="@Model.BelgeNoId" />
    @Html.AntiForgeryToken()
    <table class="table table-bordered">
        <tbody>
            <tr>
                <td>
                    <label for="AdSoyad" class="form-label">Adı Soyadı</label>
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fas fa-user"></i></span>
                        </div>
                        <input type="text" class="form-control" id="AdSoyad" name="AdSoyad"
                               placeholder="Adı Soyadı" maxlength="100"
                               value="@(Model?.AdSoyad ?? "")"
                               oninput="this.value = this.value.toLocaleUpperCase('tr-TR');">
                    </div>
                </td>
                <td>
                    <label for="inputMahalle" class="form-label">Mahalle</label>
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fas fa-map-marker-alt"></i></span>
                        </div>
                        @Html.DropDownListFor(model => model.Mahalle,
                                 (IEnumerable<SelectListItem>)ViewBag.MahalleListesi,
                                 new { @class = "form-control", id = "inputMahalle", required = "required" })
                    </div>
                    <span class="text-danger" id="mahalleError" style="display: none;">Lütfen bir mahalle seçiniz!</span>
                </td>
            </tr>
            <tr>
                <td>
                    <label for="DisKapi" class="form-label">Dış Kapı No</label>
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fas fa-door-open"></i></span>
                        </div>
                        <input type="text" class="form-control" id="DisKapi" name="DisKapi"
                               placeholder="Dış Kapı No" maxlength="4"
                               value="@(Model?.DisKapi ?? "")"
                               oninput="this.value = this.value.toLocaleUpperCase('tr-TR');">
                    </div>
                </td>
                <td>
                    <label for="İcKapiNo" class="form-label">İç Kapı No</label>
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fas fa-door-closed"></i></span>
                        </div>
                        <input type="text" class="form-control" id="IcKapiNo" name="IcKapiNo"
                               placeholder="İç Kapı No" maxlength="4"
                               value="@(Model?.IcKapiNo ?? "")"
                               oninput="this.value = this.value.replace(/[^0-9]/g, '').slice(0, 4);">
                    </div>
                </td>
            </tr>
            <tr>
                <td>
                    <label for="Ada" class="form-label">Ada</label>
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fas fa-map"></i></span>
                        </div>
                        <input type="text" class="form-control" id="Ada" name="Ada" placeholder="Ada" value="@Model.Ada" maxlength="6">
                    </div>
                </td>
                <td>
                    <label for="Parsel" class="form-label">Parsel</label>
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fas fa-map"></i></span>
                        </div>
                        <input type="text" class="form-control" id="Parsel" name="Parsel" placeholder="Parsel" value="@Model.Parsel" maxlength="6">
                    </div>
                </td>
            </tr>
            <tr>
                <td>
                    <label for="CaddeSokak" class="form-label">Cadde/Sokak</label>
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fas fa-road"></i></span>
                        </div>
                        <input type="text" class="form-control" id="CaddeSokak" name="CaddeSokak"
                               placeholder="Cadde/Sokak" maxlength="100"
                               value="@(Model?.CaddeSokak ?? "")"
                               oninput="this.value = this.value.toLocaleUpperCase('tr-TR');">
                    </div>
                </td>
            </tr>
            <tr>
                <td colspan="2" class="text-center">
                    <button type="submit" class="btn btn-primary">Güncelle</button>
                </td>

                <td>
                    <input type="hidden" id="Tarih" name="Tarih" value="@Model.Tarih" />
                </td>
            </tr>
        </tbody>
    </table>
</form>

<script>
    document.addEventListener('DOMContentLoaded', function () {
        const today = new Date();

        // Yerel saat dilimine göre tarih ve saat formatı
        const offset = today.getTimezoneOffset() * 60000; // dakika cinsinden offset'i milisaniyeye çevir
        const localTime = new Date(today.getTime() - offset);

        // Formatlayarak tarih ve saati al
        const formattedDate = localTime.toISOString().substring(0, 16);
        document.getElementById('Tarih').value = formattedDate;
    });
</script>
<script>
    document.addEventListener('DOMContentLoaded', function () {
        const form = document.getElementById('sahaCalismasiForm');

        form.addEventListener('input', function (event) {
            const input = event.target;

            // Yalnızca metin ve telefon alanlarında dönüşüm yap
            if (input.type === 'text' || input.type === 'tel') {
                input.value = input.value.toLocaleUpperCase('tr-TR'); // Türkçe büyük harf dönüştürme
            }
        });

        form.addEventListener('submit', function (event) {
            // Submit sırasında bir daha kontrol etmek için
            const inputs = form.querySelectorAll('input');
            inputs.forEach(function (input) {
                if (input.type === 'text' || input.type === 'tel') {
                    input.value = input.value.toLocaleUpperCase('tr-TR');
                }
            });
        });
    });
</script>